"""
Agent 2.5: Database Migration & Multi-DB Agent

Handles database-specific configurations, migrations, and multi-tenancy (MTX).
Generates HANA-native artifacts (.hdbview, .hdbrole) when applicable,
and Alembic-style migration scripts for SQLite/PostgreSQL.
"""

import logging
from datetime import datetime
from typing import Any

from backend.agents.progress import log_progress
from backend.agents.state import BuilderState, GeneratedFile, ValidationError

logger = logging.getLogger(__name__)

async def db_migration_agent(state: BuilderState) -> BuilderState:
    """
    Database Migration Agent
    Generates DB-specific artifacts and migration scripts.
    """
    logger.info("Starting DB Migration Agent")

    now = datetime.utcnow().isoformat()
    errors: list[ValidationError] = []
    generated_files: list[GeneratedFile] = []

    state["current_agent"] = "db_migration"
    state["updated_at"] = now
    state["current_logs"] = []

    log_progress(state, "Starting database migration config...")

    db_type = state.get("database_type", "sqlite")
    mtx_enabled = state.get("multitenancy_enabled", False)
    entities = state.get("entities", [])
    namespace = state.get("project_namespace", "com.company.app")

    if not entities:
         log_progress(state, "No entities found to generate migrations for.")
         return state

    # 1. Multi-Tenancy (MTX) Configuration if enabled
    if mtx_enabled:
        log_progress(state, "Generating Multi-Tenancy (MTX) artifacts...")
        # Add basic MTX config to package.json (simulated here via a specific artifact or later in deployment)
        generated_files.append({
            "path": "db/mtx.json",
            "content": '{\n  "tenant_provisioning": true\n}',
            "file_type": "json"
        })

    # 2. HANA-native artifacts (if HANA selected or MTX enabled requiring separate tenant HDI containers)
    if db_type == "hana" or mtx_enabled:
        log_progress(state, "Generating HANA-native artifacts (.hdbview, .hdbrole)...")
        for entity in entities:
             name = entity.get("name", "")
             if name:
                 # Generate a dummy calculation view representation for demonstration
                 view_content = f'VIEW "{namespace}_{name}View" AS SELECT * FROM "{namespace}.{name}"'
                 generated_files.append({
                     "path": f"db/src/gen/{name}.hdbview",
                     "content": view_content,
                     "file_type": "hdbview"
                 })
                 
        admin_role_entity = entities[0].get('name', 'Entity') if entities else 'Unknown'
        role_content = f'''{{
  "role": {{
    "name": "{namespace}::admin",
    "object_privileges": [
      {{
        "name": "{namespace}.{admin_role_entity}",
        "type": "TABLE",
        "privileges": [ "SELECT", "INSERT", "UPDATE", "DELETE" ]
      }}
    ]
  }}
}}'''
        generated_files.append({
            "path": "db/src/roles/admin.hdbrole",
            "content": role_content,
            "file_type": "json"
        })

    # 3. Standard local migrations (simulate Alembic or CDS migrate)
    if db_type == "sqlite":
         log_progress(state, "Generating standard migration scripts...")
         generated_files.append({
            "path": "db/migrations/001_initial_schema.sql",
            "content": "-- Initial Schema Migration\n-- Auto-generated by CDS\n",
            "file_type": "sql"
        })

    # Append new files to state
    existing_db = state.get("artifacts_db", [])
    state["artifacts_db"] = existing_db + generated_files
    
    # Store history
    state["agent_history"] = state.get("agent_history", []) + [{
        "agent_name": "db_migration",
        "status": "completed",
        "started_at": now,
        "completed_at": datetime.utcnow().isoformat(),
        "duration_ms": None,
        "error": None,
        "logs": state.get("current_logs", []),
    }]

    log_progress(state, f"DB migration configs generated ({len(generated_files)} files).")
    return state
