"""
Shared LLM Utilities for All Agents

Provides common functions for LLM generation with retry logic,
robust JSON parsing, and inter-agent context helpers.

Used by all agents to eliminate duplicate code and ensure consistent
LLM interaction patterns.
"""

import json
import logging
import asyncio
import random
from typing import Any

from backend.agents.llm_providers import get_llm_manager
from backend.agents.state import BuilderState
from backend.agents.progress import log_progress
from backend.agents.model_router import get_model_for_agent, get_model_tier_name

logger = logging.getLogger(__name__)


# =============================================================================
# Robust JSON Parsing
# =============================================================================

def parse_llm_json(response_text: str) -> dict | None:
    """
    Robustly parse JSON from LLM response.
    Handles markdown code fences, extra text, and common formatting issues.
    """
    if not response_text:
        return None

    text = response_text.strip()
    
    # Strip <think>...</think> tags which are generated by Deepseek reasoning models
    import re
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()

    # 1. Try direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # 2. Extract from markdown code fence
    try:
        if "```json" in text:
            json_str = text.split("```json", 1)[1].split("```", 1)[0].strip()
            return json.loads(json_str)
        elif "```" in text:
            json_str = text.split("```", 1)[1].split("```", 1)[0].strip()
            return json.loads(json_str)
    except (json.JSONDecodeError, IndexError):
        pass

    # 3. Find first { ... last }
    try:
        start = text.index("{")
        end = text.rindex("}") + 1
        return json.loads(text[start:end])
    except (ValueError, json.JSONDecodeError):
        pass

    return None


# =============================================================================
# LLM Generation with Retry and Self-Healing
# =============================================================================

async def generate_with_retry(
    prompt: str,
    system_prompt: str,
    state: BuilderState,
    required_keys: list[str] | None = None,
    max_retries: int = 5,
    agent_name: str = "agent",
) -> dict | None:
    """
    Call LLM with retry logic and self-healing.

    If JSON parsing fails or required keys are missing, feeds the error
    back to the LLM for correction.

    Args:
        prompt: The user/generation prompt
        system_prompt: System prompt with instructions
        state: Current BuilderState (for provider and logging)
        required_keys: Keys that must be present in the JSON response
        max_retries: Maximum number of retry attempts
        agent_name: Name of the calling agent (for logging)

    Returns:
        Parsed JSON dict or None if all attempts fail
    """
    llm_manager = get_llm_manager()
    
    # IMPORTANT: Use the user's selected provider and model from state
    provider = state.get("llm_provider")
    user_model = state.get("llm_model")  # User's selected model from frontend
    
    last_error = None
    
    # Get tier name for logging (Strategic vs Efficient)
    tier_name = get_model_tier_name(agent_name)
    
    # Store model tier in state for tracking
    if "model_tier" not in state:
        state["model_tier"] = {}
    state["model_tier"][agent_name] = tier_name
    
    # Determine the actual provider and model name for logging
    actual_provider = provider or llm_manager.settings.default_llm_provider
    model_name = user_model or "default"
    model_tag = f"[{actual_provider}/{tier_name}/{model_name}]"

    # Inject complexity-level instructions into the prompt
    complexity_instructions = get_complexity_prompt(state)
    current_prompt = f"{complexity_instructions}\n\n{prompt}"

    for attempt in range(max_retries):
        try:
            # Use the user's selected model - NO OVERRIDE
            response = await llm_manager.generate(
                prompt=current_prompt,
                system_prompt=system_prompt,
                provider=provider,
                model=user_model,  # Pass user's model directly
                temperature=0.1 if attempt == 0 else 0.05,
            )

            parsed = parse_llm_json(response)

            if parsed and isinstance(parsed, dict):
                # Check required keys if specified
                if required_keys:
                    missing = [k for k in required_keys if k not in parsed or not parsed[k]]
                    if missing:
                        last_error = f"Missing required keys: {missing}"
                        log_progress(state, f"⚠️ {model_tag} [{agent_name}] Attempt {attempt + 1}: {last_error}. Retrying...")

                        if attempt < max_retries - 1:
                            current_prompt = f"""Your previous response was missing required keys: {missing}

Previous response (first 500 chars): {response[:500]}

CRITICAL: Your JSON response MUST contain these keys: {required_keys}
Respond with ONLY valid JSON. No markdown, no extra text.

{prompt}"""
                        continue
                
                log_progress(state, f"✅ {model_tag} [{agent_name}] LLM generation successful (attempt {attempt + 1}).")
                return parsed
            else:
                last_error = "Could not parse JSON from response"
                log_progress(state, f"⚠️ {model_tag} [{agent_name}] Attempt {attempt + 1}: {last_error}. Retrying...")

            # Build correction prompt for next attempt
            if attempt < max_retries - 1:
                current_prompt = f"""Your previous response could not be parsed as JSON. Error: {last_error}

Previous response (first 500 chars): {response[:500]}

CRITICAL: You MUST respond with ONLY valid JSON. No markdown formatting, no explanation text.
Start your response with {{ and end with }}.

{prompt}"""

        except Exception as e:
            last_error = str(e)
            is_rate_limit = "429" in last_error or "rate" in last_error.lower() or "quota" in last_error.lower()
            
            if is_rate_limit:
                # Exponential backoff for rate limit errors: 5s, 10s, 20s
                backoff = (5 * (2 ** attempt)) + random.uniform(0.5, 2.0)
                logger.warning(f"[{agent_name}] Rate limit hit (attempt {attempt + 1}). Backing off {backoff:.1f}s...")
                log_progress(state, f"⚠️ {model_tag} [{agent_name}] Attempt {attempt + 1} error: Error code: 429 - {str(e)[:80]}. Retrying...")
                await asyncio.sleep(backoff)
            else:
                logger.warning(f"[{agent_name}] LLM attempt {attempt + 1} failed: {e}")
                log_progress(state, f"⚠️ {model_tag} [{agent_name}] Attempt {attempt + 1} error: {str(e)[:100]}. Retrying...")
                # Small delay even for non-rate-limit errors
                await asyncio.sleep(2)

            if attempt < max_retries - 1:
                current_prompt = f"{complexity_instructions}\n\n{prompt}"  # Reset with complexity prefix

    logger.error(f"[{agent_name}] All {max_retries} LLM attempts failed. Last error: {last_error}")
    return None


# =============================================================================
# Inter-Agent Context Helpers
# =============================================================================

def get_schema_context(state: BuilderState) -> str:
    """Get the generated schema CDS for downstream agents."""
    schema = state.get("generated_schema_cds", "")
    common = state.get("generated_common_cds", "")
    if schema:
        ctx = "GENERATED CDS SCHEMA (from Data Modeling Agent):\n```cds\n"
        if common:
            ctx += f"// db/common.cds\n{common}\n\n"
        ctx += f"// db/schema.cds\n{schema}\n```\n"
        return ctx
    return ""


def get_service_context(state: BuilderState) -> str:
    """Get the generated service CDS for downstream agents."""
    service = state.get("generated_service_cds", "")
    annotations = state.get("generated_annotations_cds", "")
    if service:
        ctx = "GENERATED SERVICE DEFINITION (from Service Exposure Agent):\n```cds\n"
        ctx += f"// srv/service.cds\n{service}\n"
        if annotations:
            ctx += f"\n// srv/annotations.cds\n{annotations}\n"
        ctx += "```\n"
        return ctx
    return ""


def get_handler_context(state: BuilderState) -> str:
    """Get the generated handler JS for downstream agents."""
    handler = state.get("generated_handler_js", "")
    if handler:
        return f"GENERATED SERVICE HANDLER (from Business Logic Agent):\n```javascript\n{handler}\n```\n"
    return ""


def get_architecture_context(state: BuilderState) -> str:
    """Get the enterprise architecture blueprint for downstream agents."""
    architecture = state.get("architecture_context_md", "")
    if architecture:
        return f"ENTERPRISE ARCHITECTURE BLUEPRINT:\n{architecture}\n"
    return ""


def get_full_context(state: BuilderState) -> str:
    """Get all available inter-agent context."""
    parts = []
    architecture_ctx = get_architecture_context(state)
    if architecture_ctx:
        parts.append(architecture_ctx)
    schema_ctx = get_schema_context(state)
    if schema_ctx:
        parts.append(schema_ctx)
    service_ctx = get_service_context(state)
    if service_ctx:
        parts.append(service_ctx)
    handler_ctx = get_handler_context(state)
    if handler_ctx:
        parts.append(handler_ctx)
    return "\n".join(parts)


def get_complexity_prompt(state: BuilderState) -> str:
    """
    Get complexity-specific instructions to inject into agent prompts.
    This controls the depth, richness, and enterprise-level features each agent generates.
    """
    level = state.get("complexity_level", "standard")
    
    prompts = {
        "starter": """
COMPLEXITY LEVEL: STARTER (Lightweight / Getting Started)
- Generate 2-3 entities maximum with 4-6 fields each
- Basic CRUD operations only — no custom actions
- Simple validations (required fields, type checks)
- No workflow state machines
- Mock authentication only
- Minimal annotations (@title on key fields)
- No sample data CSV files
- Skip CI/CD configuration
- Single Fiori List Report app
""",
        "standard": """
COMPLEXITY LEVEL: STANDARD (Production-Ready)
- Generate 4-6 entities with 6-12 fields each
- Include Draft support for editing scenarios
- Input validations (format, range, required)
- Status field with 3-5 state transitions
- Auto-numbering for business identifiers
- RBAC with Viewer/Editor/Admin roles
- Rich Fiori annotations (@UI.LineItem, @UI.HeaderInfo, @UI.FieldGroup, @UI.SelectionField)
- Generate sample data CSV files (5-8 rows per entity)
- Include @Common.ValueList for association fields
- Basic deployment config (mta.yaml, package.json)
""",
        "enterprise": """
COMPLEXITY LEVEL: ENTERPRISE (Industry-Grade)
- Generate 6-10 entities with 8-15 fields each including domain-specific fields
- Full Draft workflow with complex lifecycle
- Multi-level approval workflows (Draft→Submitted→Approved→InProcess→Completed)
- Approval/Rejection actions with comments and history tracking
- Advanced validations: cross-field, cross-entity, date range, business rule checks
- Auto-numbering with company code and fiscal year (e.g., PO-2026-US-00001)
- Audit trail fields (changedBy, changedAt, changeReason)
- Calculated/virtual fields (totalAmount, remainingBudget, daysOverdue)
- Cascading calculations (parent totals from child line items)
- Side effects: @Common.SideEffects for reactive form updates
- Rich Fiori annotations: @UI.Chart, @UI.DataPoint with criticality, @UI.PresentationVariant
- @Capabilities annotations (InsertRestrictions, DeleteRestrictions, FilterRestrictions)
- Multiple value helps with @Common.ValueList
- Structured error handling with domain-specific error codes
- Generate comprehensive sample data (8-12 rows with realistic values)
- Full deployment config with CI/CD
- Extension hooks for SAP Clean Core compliance
""",
        "full_stack": """
COMPLEXITY LEVEL: FULL STACK (Maximum Enterprise Features)
- Generate 8-15 entities with 10-20 fields each — think real enterprise ERP modules
- Everything from ENTERPRISE level, PLUS:
- Analytical annotations: @Aggregation, @Analytics.Measure for reporting views
- Scheduled background job patterns (batch close, reminder notifications)
- Event-driven patterns: emit domain events on critical state changes
- Multi-service architecture: separate catalog/admin/analytics services
- API versioning consideration in service paths
- Feature flag entity for runtime configuration
- Comprehensive i18n with multiple languages
- Full test scaffolding: unit test stubs, integration test patterns
- Docker and CI/CD pipeline configs (GitHub Actions)
- Health check and monitoring endpoints
- Comprehensive documentation (ARCHITECTURE.md, API.md, DEVELOPMENT.md)
- Custom Fiori fragments and extensions
- Data import/export actions for bulk operations
"""
    }
    
    return prompts.get(level, prompts["standard"])


def store_generated_content(state: BuilderState, artifacts: list, key_map: dict[str, str]) -> None:
    """
    Store generated file content in state for inter-agent context.

    Args:
        state: BuilderState to update
        artifacts: List of GeneratedFile dicts
        key_map: Mapping of file path patterns to state keys
                 e.g., {"schema.cds": "generated_schema_cds"}
    """
    for artifact in artifacts:
        path = artifact.get("path", "")
        content = artifact.get("content", "")
        for pattern, state_key in key_map.items():
            if pattern in path:
                state[state_key] = content
                break
