"""
Agent 1: Requirements & Domain Agent (LLM-First Architecture)

Collects, analyzes, normalizes, and validates business requirements.
Transforms user intent into structured, SAP-compatible specifications.

FULLY LLM-DRIVEN: No hardcoded domain templates. Every project is unique
based on the user's description, entity names, and domain context.
"""

import json
import logging
import asyncio
import random
from datetime import datetime
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage

from backend.agents.llm_providers import get_llm_manager
from backend.agents.state import (
    BuilderState,
    EntityDefinition,
    FieldDefinition,
    RelationshipDefinition,
    BusinessRule,
    DomainType,
    ValidationError,
)

logger = logging.getLogger(__name__)


# =============================================================================
# Helpers
# =============================================================================

from backend.agents.progress import log_progress


# =============================================================================
# JSON Parsing Utility
# =============================================================================

def _parse_llm_json(response_text: str) -> dict | None:
    """
    Robustly parse JSON from LLM response.
    Handles markdown code fences, extra text, and common formatting issues.
    """
    if not response_text:
        return None

    text = response_text.strip()
    
    # Strip <think>...</think> tags which are generated by Deepseek reasoning models
    import re
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()

    # 1. Try direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # 2. Extract from markdown code fence
    try:
        if "```json" in text:
            json_str = text.split("```json", 1)[1].split("```", 1)[0].strip()
            return json.loads(json_str)
        elif "```" in text:
            json_str = text.split("```", 1)[1].split("```", 1)[0].strip()
            return json.loads(json_str)
    except (json.JSONDecodeError, IndexError):
        pass

    # 3. Find first { ... last }
    try:
        start = text.index("{")
        end = text.rindex("}") + 1
        return json.loads(text[start:end])
    except (ValueError, json.JSONDecodeError):
        pass

    return None


# =============================================================================
# System Prompt — Comprehensive Requirements Architect
# =============================================================================

REQUIREMENTS_SYSTEM_PROMPT = """You are a world-class SAP CAP (Cloud Application Programming Model) enterprise architect.
Your task is to analyze ANY business domain and produce complete, production-grade entity specifications.

You must generate entities that are SPECIFIC to the user's domain — not generic CRUD entities.

STRICT RULES:
1. Use ONLY official SAP CAP CDS types: UUID, String, Integer, Int64, Decimal, Double, Boolean, Date, DateTime, Time, Timestamp, LargeString, LargeBinary
2. Follow SAP naming: PascalCase for entities, camelCase for fields
3. Every entity MUST have: { "name": "ID", "type": "UUID", "key": true, "nullable": false } as the first field
4. Include "aspects": ["cuid", "managed"] for root entities (adds createdAt, modifiedAt, createdBy, modifiedBy audit fields)
5. For child entities in compositions, use "aspects": ["cuid"] (no managed — parent tracks audit)
6. For String fields, ALWAYS include "length" (typical: 10-255, use 500+ for URLs)
7. For Decimal fields, ALWAYS include "precision" and "scale"
8. Use sensible defaults for status fields (e.g., "'Draft'", "'Active'", "'New'")
9. Use proper CDS default syntax: strings as "'value'" (with inner single quotes), numbers as "0", booleans as "true"/"false"

DOMAIN ANALYSIS — For EVERY domain, generate:
1. **Core business entities** — The primary objects (e.g., Patient, Appointment, MedicalRecord for healthcare)
2. **Transactional entities** — Business events/transactions (e.g., Billing, Prescription, LabResult)
3. **Master data entities** — Reference/lookup data (e.g., Department, Doctor, InsurancePlan)
4. **Junction/child entities** — Line items, details (e.g., PrescriptionItem, DiagnosisCode)

FIELD GENERATION — For EVERY entity, consider:
- Unique business identifiers (orderNumber, patientId, invoiceRef) — String with length
- Status/workflow fields with meaningful states
- Date/time fields for business events (submittedAt, scheduledDate, dueDate)
- Financial fields with Decimal type (amount, tax, discount)
- Currency fields as String(3) with ISO 4217 defaults
- Contact fields (email, phone) with @Semantics annotations
- Category/classification fields
- Priority/criticality indicators
- Notes/comments as LargeString
- Quantity/count fields as Integer
- Boolean flags (isActive, isPrimary, isUrgent)

RELATIONSHIP GENERATION:
- Use "composition" for parent-child ownership (Order→OrderItem, Invoice→InvoiceLineItem)
  - Compositions mean child cannot exist without parent
  - Child entity gets a back-reference field automatically
- Use "association" for references between independent entities (Order→Customer, Employee→Department)
- Cardinality: "1:n" for one-to-many, "n:1" for many-to-one, "1:1" for one-to-one
- Name associations by the TARGET entity in camelCase singular/plural

BUSINESS RULES — Generate domain-specific rules:
- rule_type: "validation" — Field validations (date ranges, value bounds, format checks, required combinations)
- rule_type: "calculation" — Derived/computed fields (totalAmount = sum of items, remainingBudget = allocated - spent)
- rule_type: "workflow" — Status state machines with valid transitions (Draft→Submitted→Approved→Completed)
- rule_type: "auto_number" — Sequential ID generation (INV-2024-0001, ORD-YYYYMMDD-XXXX)
- rule_type: "side_effect" — Cascading actions (update parent totals when child changes, update inventory on shipment)
- rule_type: "action" — Custom business actions (approve, reject, escalate, convert, assign)

OUTPUT FORMAT — Respond with ONLY valid JSON:
{
  "entities": [
    {
      "name": "EntityName",
      "description": "Clear business description",
      "fields": [
        {"name": "ID", "type": "UUID", "key": true, "nullable": false},
        {"name": "fieldName", "type": "String", "length": 100, "nullable": false, "annotations": {"title": "Human Label"}},
        ...
      ],
      "aspects": ["cuid", "managed"]
    }
  ],
  "relationships": [
    {"name": "relName", "source_entity": "Source", "target_entity": "Target", "type": "association|composition", "cardinality": "n:1|1:n|1:1"}
  ],
  "business_rules": [
    {"name": "ruleName", "entity": "EntityName", "rule_type": "validation|calculation|workflow|auto_number|side_effect|action", "description": "What this rule does"}
  ]
}"""


DOMAIN_ANALYSIS_PROMPT = """Analyze this project and generate COMPLETE, PRODUCTION-GRADE entity definitions.

Project Name: {project_name}
Project Description: {description}
Domain Hint: {domain_type}
{entity_context}

REQUIREMENTS:
1. Generate 4-8 entities that accurately model this business domain
2. Each entity must have 6-15 fields that are SPECIFIC to the domain (not just ID + name + status)
3. Generate ALL relationships between entities (both associations and compositions)
4. Generate domain-specific business rules (validations, calculations, workflows, auto-numbering)
5. Think about what a REAL enterprise application would need — not a tutorial/demo

{additional_context}

Respond with ONLY valid JSON matching the schema described in the system prompt."""


FIELD_GENERATION_PROMPT = """Generate COMPLETE field definitions for these entities in a {project_name} application.

Project Description: {description}
Domain: {domain_type}

Entities requiring field generation:
{entities_json}

REQUIREMENTS:
1. For each entity, generate 6-15 domain-specific fields
2. ALWAYS start with: {{"name": "ID", "type": "UUID", "key": true, "nullable": false}}
3. Include business identifiers, status fields, date fields, amount fields as appropriate
4. Add proper annotations: {{"title": "Human Readable Label"}} on important fields
5. Use correct CDS types and include length/precision/scale where required
6. Also generate relationships between these entities
7. Generate business rules (validations, calculations, workflows)

Respond with ONLY valid JSON:
{{
  "entities": [...],
  "relationships": [...],
  "business_rules": [...]
}}"""


# =============================================================================
# Validation Functions (kept and enhanced)
# =============================================================================

def validate_project_name(name: str) -> list[ValidationError]:
    """Validate project name follows SAP conventions."""
    errors: list[ValidationError] = []

    if not name:
        errors.append({
            "agent": "requirements",
            "code": "PROJECT_NAME_REQUIRED",
            "message": "Project name is required",
            "field": "project_name",
            "severity": "error",
        })
        return errors

    if len(name) < 3:
        errors.append({
            "agent": "requirements",
            "code": "PROJECT_NAME_TOO_SHORT",
            "message": "Project name must be at least 3 characters",
            "field": "project_name",
            "severity": "error",
        })

    if len(name) > 50:
        errors.append({
            "agent": "requirements",
            "code": "PROJECT_NAME_TOO_LONG",
            "message": "Project name must be 50 characters or less",
            "field": "project_name",
            "severity": "error",
        })

    if not name[0].isalpha():
        errors.append({
            "agent": "requirements",
            "code": "PROJECT_NAME_INVALID_START",
            "message": "Project name must start with a letter",
            "field": "project_name",
            "severity": "error",
        })

    if not all(c.isalnum() or c in "-_ " for c in name):
        errors.append({
            "agent": "requirements",
            "code": "PROJECT_NAME_INVALID_CHARS",
            "message": "Project name can only contain letters, numbers, spaces, hyphens, and underscores",
            "field": "project_name",
            "severity": "error",
        })

    return errors


def validate_entity_name(name: str) -> list[ValidationError]:
    """Validate entity name follows CDS conventions."""
    errors: list[ValidationError] = []

    if not name:
        errors.append({
            "agent": "requirements",
            "code": "ENTITY_NAME_REQUIRED",
            "message": "Entity name is required",
            "field": "entity_name",
            "severity": "error",
        })
        return errors

    # Must be PascalCase (start with uppercase)
    if not name[0].isupper():
        errors.append({
            "agent": "requirements",
            "code": "ENTITY_NAME_NOT_PASCAL_CASE",
            "message": f"Entity name '{name}' must start with uppercase (PascalCase)",
            "field": "entity_name",
            "severity": "warning",
        })

    # Only alphanumeric
    if not name.isalnum():
        errors.append({
            "agent": "requirements",
            "code": "ENTITY_NAME_INVALID_CHARS",
            "message": f"Entity name '{name}' can only contain letters and numbers",
            "field": "entity_name",
            "severity": "error",
        })

    return errors


def validate_entities(entities: list[EntityDefinition]) -> list[ValidationError]:
    """Validate entity definitions."""
    errors: list[ValidationError] = []

    if not entities:
        errors.append({
            "agent": "requirements",
            "code": "NO_ENTITIES",
            "message": "At least one entity must be defined",
            "field": "entities",
            "severity": "error",
        })
        return errors

    entity_names = set()
    for entity in entities:
        name = entity.get("name", "")

        # Check for duplicate names
        if name in entity_names:
            errors.append({
                "agent": "requirements",
                "code": "DUPLICATE_ENTITY_NAME",
                "message": f"Duplicate entity name: {name}",
                "field": "entities",
                "severity": "error",
            })
        entity_names.add(name)

        # Validate entity name
        errors.extend(validate_entity_name(name))

        # Check for key field
        fields = entity.get("fields", [])
        has_key = any(f.get("key", False) for f in fields)
        if fields and not has_key:
            errors.append({
                "agent": "requirements",
                "code": "NO_KEY_FIELD",
                "message": f"Entity '{name}' must have at least one key field",
                "field": "entities",
                "severity": "error",
            })

    return errors


def _ensure_entity_quality(entities: list) -> list:
    """Post-process LLM output to ensure minimum quality standards."""
    for entity in entities:
        fields = entity.get("fields", [])

        # Ensure ID field exists as first field
        has_id = any(f.get("name") == "ID" and f.get("key") for f in fields)
        if not has_id:
            fields.insert(0, {"name": "ID", "type": "UUID", "key": True, "nullable": False})
            entity["fields"] = fields

        # Ensure aspects are set
        if not entity.get("aspects"):
            entity["aspects"] = ["cuid", "managed"]

        # Ensure String fields have length
        for field in fields:
            if field.get("type") == "String" and not field.get("length"):
                field["length"] = 100  # sensible default
            if field.get("type") == "Decimal":
                if not field.get("precision"):
                    field["precision"] = 12
                if not field.get("scale"):
                    field["scale"] = 2

    return entities


# =============================================================================
# LLM Generation with Retry
# =============================================================================

async def _generate_with_retry(
    prompt: str,
    system_prompt: str,
    provider: str | None,
    state: BuilderState,
    max_retries: int = 3,
) -> dict | None:
    """
    Call LLM with retry logic and self-healing.
    If JSON parsing fails, feeds the error back to the LLM.
    """
    from backend.agents.llm_utils import get_complexity_prompt
    
    llm_manager = get_llm_manager()
    last_error = None

    # Inject complexity-level instructions into the prompt
    complexity_instructions = get_complexity_prompt(state)
    current_prompt = f"{complexity_instructions}\n\n{prompt}"

    for attempt in range(max_retries):
        try:
            response = await llm_manager.generate(
                prompt=current_prompt,
                system_prompt=system_prompt,
                provider=provider,
                temperature=0.1 if attempt == 0 else 0.05,  # Lower temp on retries
            )

            parsed = _parse_llm_json(response)

            if parsed and isinstance(parsed, dict):
                # Basic structural validation
                entities = parsed.get("entities", [])
                if entities and len(entities) > 0:
                    log_progress(state, f"✅ LLM generated {len(entities)} entities (attempt {attempt + 1}).")
                    return parsed
                else:
                    last_error = "Response contained empty entities list"
                    log_progress(state, f"⚠️ Attempt {attempt + 1}: {last_error}. Retrying...")
            else:
                last_error = "Could not parse JSON from response"
                log_progress(state, f"⚠️ Attempt {attempt + 1}: {last_error}. Retrying...")

            # Build correction prompt for next attempt
            if attempt < max_retries - 1:
                current_prompt = f"""Your previous response could not be used. Error: {last_error}

Previous response (first 500 chars): {response[:500]}

CRITICAL: You MUST respond with ONLY valid JSON. No markdown, no explanation, no text before or after the JSON.
Start your response with {{ and end with }}.

{prompt}"""

        except Exception as e:
            last_error = str(e)
            is_rate_limit = "429" in last_error or "rate" in last_error.lower() or "quota" in last_error.lower()
            
            if is_rate_limit:
                backoff = (5 * (2 ** attempt)) + random.uniform(0.5, 2.0)
                logger.warning(f"Rate limit hit (attempt {attempt + 1}). Backing off {backoff:.1f}s...")
                log_progress(state, f"⚠️ Attempt {attempt + 1} error: Error code: 429 - {str(e)[:80]}. Retrying...")
                await asyncio.sleep(backoff)
            else:
                logger.warning(f"LLM attempt {attempt + 1} failed: {e}")
                log_progress(state, f"⚠️ Attempt {attempt + 1} error: {str(e)[:100]}. Retrying...")
                await asyncio.sleep(2)

            if attempt < max_retries - 1:
                current_prompt = f"{complexity_instructions}\n\n{prompt}"  # Reset with complexity prefix

    logger.error(f"All {max_retries} LLM attempts failed. Last error: {last_error}")
    return None


# =============================================================================
# Main Agent Function
# =============================================================================

async def requirements_agent(state: BuilderState) -> BuilderState:
    """
    Requirements & Domain Agent (LLM-First)

    ALWAYS uses LLM to generate domain-specific entity definitions.
    No hardcoded domain templates — every project gets a unique,
    contextually appropriate data model.

    Processes:
    1. Validates project configuration
    2. Uses LLM to generate entities, relationships, and business rules
    3. Post-processes output for quality assurance
    4. Validates final entities

    Returns updated state with entities, relationships, and business rules.
    """
    logger.info("Starting Requirements Agent (LLM-First)")

    now = datetime.utcnow().isoformat()
    errors: list[ValidationError] = []

    # Update state
    state["current_agent"] = "requirements"
    state["updated_at"] = now
    state["current_logs"] = []

    log_progress(state, "Analyzing project configuration...")

    # ==========================================================================
    # Step 1: Validate project configuration
    # ==========================================================================
    project_name = state.get("project_name", "")
    errors.extend(validate_project_name(project_name))

    if any(e["severity"] == "error" for e in errors):
        state["validation_errors"] = errors
        logger.error(f"Validation failed: {errors}")
        log_progress(state, f"Validation failed: {errors[0]['message']}")
        return state

    # ==========================================================================
    # Step 2: Determine what generation is needed
    # ==========================================================================
    domain_type = state.get("domain_type", DomainType.CUSTOM.value)
    description = state.get("project_description", "")
    provider = state.get("llm_provider")
    user_entities = state.get("entities", [])

    # Determine if user entities have full field definitions
    entities_have_fields = user_entities and all(
        len(e.get("fields", [])) > 1 for e in user_entities  # More than just ID
    )

    if entities_have_fields:
        # ======================================================================
        # Path A: User provided complete entities — validate only
        # ======================================================================
        log_progress(state, "Validating user-defined entities...")
        errors.extend(validate_entities(user_entities))

        # Still use LLM to generate relationships and business rules if missing
        if not state.get("relationships") or not state.get("business_rules"):
            log_progress(state, "Generating relationships and business rules for existing entities...")
            entity_names = [e.get("name", "") for e in user_entities]
            entity_descs = [f"{e.get('name', '')}: {e.get('description', '')}" for e in user_entities]

            field_summaries = []
            for e in user_entities:
                fields = e.get("fields", [])
                field_names = []
                for f in fields:
                    if isinstance(f, dict):
                        field_names.append(f.get("name", ""))
                    else:
                        field_names.append(str(f))
                field_summaries.append({
                    "name": e.get("name", ""),
                    "fields": field_names
                })
            
            try:
                fields_json = json.dumps(field_summaries, indent=2)
            except Exception:
                fields_json = "[]"
                
            try:
                entities_json = json.dumps(user_entities)
            except Exception:
                entities_json = "[]"

            rel_prompt = f"""Given these existing entities in a {project_name} application:

{chr(10).join(entity_descs)}

Entity Fields (summary):
{fields_json}

Generate relationships between these entities and business rules.

Respond with ONLY valid JSON:
{{
  "entities": {entities_json},
  "relationships": [...],
  "business_rules": [...]
}}"""

            result = await _generate_with_retry(rel_prompt, REQUIREMENTS_SYSTEM_PROMPT, provider, state, max_retries=2)
            if result:
                state["relationships"] = result.get("relationships", state.get("relationships", []))
                state["business_rules"] = result.get("business_rules", state.get("business_rules", []))
                log_progress(state, f"Generated {len(state.get('relationships', []))} relationships, {len(state.get('business_rules', []))} business rules.")

    elif user_entities and not entities_have_fields:
        # ======================================================================
        # Path B: User provided entity names only — LLM generates fields
        # ======================================================================
        entity_names = [e.get("name", "") for e in user_entities]
        log_progress(state, f"🧠 Using LLM to generate full definitions for: {', '.join(entity_names)}...")

        # Build context about entity names
        entity_context = f"User has specified these entity names: {', '.join(entity_names)}"
        additional_context = f"""IMPORTANT: You MUST include ALL of these entities in your response: {', '.join(entity_names)}
You may also add related entities if they make business sense (e.g., line item entities for header entities)."""

        prompt = DOMAIN_ANALYSIS_PROMPT.format(
            project_name=project_name,
            description=description or f"A {domain_type} business application with entities: {', '.join(entity_names)}",
            domain_type=domain_type,
            entity_context=entity_context,
            additional_context=additional_context,
        )

        result = await _generate_with_retry(prompt, REQUIREMENTS_SYSTEM_PROMPT, provider, state)

        if result:
            generated_entities = _ensure_entity_quality(result.get("entities", []))
            state["entities"] = generated_entities
            state["relationships"] = result.get("relationships", [])
            state["business_rules"] = result.get("business_rules", [])
            log_progress(state, f"✅ LLM generated {len(generated_entities)} entities with complete field definitions.")
        else:
            # This is the only fallback — but it NEVER uses templates
            log_progress(state, "⚠️ LLM generation failed after all retries. Generating minimal entities.")
            errors.append({
                "agent": "requirements",
                "code": "LLM_GENERATION_FAILED",
                "message": "LLM failed to generate entities. Minimal fallback applied — consider re-running.",
                "field": None,
                "severity": "warning",
            })
            # Minimal fallback: just ensure entities have ID field
            for entity in user_entities:
                if not entity.get("fields"):
                    entity["fields"] = [
                        {"name": "ID", "type": "UUID", "key": True, "nullable": False},
                        {"name": "name", "type": "String", "length": 100, "nullable": False},
                        {"name": "description", "type": "LargeString", "nullable": True},
                        {"name": "status", "type": "String", "length": 20, "nullable": False, "default": "'Active'"},
                    ]
                    entity["aspects"] = entity.get("aspects", ["cuid", "managed"])
            state["entities"] = user_entities

    else:
        # ======================================================================
        # Path C: No entities provided — LLM generates everything from description
        # ======================================================================
        if description or domain_type != DomainType.CUSTOM.value:
            effective_description = description or f"A comprehensive {domain_type} management application"
            log_progress(state, f"🧠 Using LLM to design entire data model for: {project_name}...")

            prompt = DOMAIN_ANALYSIS_PROMPT.format(
                project_name=project_name,
                description=effective_description,
                domain_type=domain_type,
                entity_context="No entities specified — you must identify the right entities for this domain.",
                additional_context="""Generate 4-8 entities that form a complete, realistic business application.
Think about what entities a real enterprise would need — not a basic tutorial.
Include transactional entities, master data, and line-item entities.""",
            )

            result = await _generate_with_retry(prompt, REQUIREMENTS_SYSTEM_PROMPT, provider, state)

            if result:
                generated_entities = _ensure_entity_quality(result.get("entities", []))
                state["entities"] = generated_entities
                state["relationships"] = result.get("relationships", [])
                state["business_rules"] = result.get("business_rules", [])
                log_progress(state, f"✅ LLM designed {len(generated_entities)} entities for {domain_type} domain.")
            else:
                log_progress(state, "❌ LLM generation failed after all retries.")
                errors.append({
                    "agent": "requirements",
                    "code": "LLM_GENERATION_FAILED",
                    "message": "Could not generate entities. Please check your LLM API key and try again.",
                    "field": None,
                    "severity": "error",
                })
        else:
            log_progress(state, "No entities or description provided.")
            errors.append({
                "agent": "requirements",
                "code": "NO_INPUT",
                "message": "Please provide either entity names or a project description",
                "field": None,
                "severity": "error",
            })

    # ==========================================================================
    # Step 3: Final validation
    # ==========================================================================
    log_progress(state, "Performing final validation...")
    errors.extend(validate_entities(state.get("entities", [])))

    # ==========================================================================
    # Step 4: Set main entity for Fiori if not set
    # ==========================================================================
    if not state.get("fiori_main_entity") and state.get("entities"):
        state["fiori_main_entity"] = state["entities"][0].get("name", "")

    # ==========================================================================
    # Step 5: Update state
    # ==========================================================================
    state["validation_errors"] = errors

    # Record execution
    state["agent_history"] = state.get("agent_history", []) + [{
        "agent_name": "requirements",
        "status": "completed" if not any(e["severity"] == "error" for e in errors) else "failed",
        "started_at": now,
        "completed_at": datetime.utcnow().isoformat(),
        "duration_ms": None,
        "error": None if not errors else str(errors[0]["message"]) if errors else None,
        "logs": state.get("current_logs", []),
    }]

    log_progress(state, "Requirements analysis complete.")
    logger.info(f"Requirements Agent completed. Entities: {len(state.get('entities', []))}, Errors: {len(errors)}")

    return state
