"""
Agent 3: CAP Service Exposure Agent (LLM-Driven)

Generates OData service definitions, projections, actions, functions,
and Fiori UI annotations for SAP CAP services.

FULLY LLM-DRIVEN with inter-agent context: reads the actual schema.cds
generated by the Data Modeling agent to produce consistent services.
"""

import json
import logging
from datetime import datetime
from typing import Any

from backend.agents.llm_providers import get_llm_manager
from backend.agents.llm_utils import (
    generate_with_retry,
    get_schema_context,
    store_generated_content,
)
from backend.agents.knowledge_loader import get_service_knowledge
from backend.agents.state import (
    BuilderState,
    GeneratedFile,
    ODataVersion,
    ValidationError,
)
from backend.agents.progress import log_progress

logger = logging.getLogger(__name__)


# =============================================================================
# System Prompt
# =============================================================================

SERVICE_SYSTEM_PROMPT = """You are a senior SAP CAP service architect with deep expertise in OData V4 and Fiori Elements.
Generate production-ready, enterprise-grade OData service definitions and Fiori annotations.

STRICT RULES:

1. SERVICE DEFINITION (srv/service.cds):
   - Import schema: `using { namespace as db } from '../db/schema';`
   - Declare: `service ServiceName @(path: '/endpoint') { ... }`
   - Use projections: `entity X as projection on db.X;`
   - Add `@odata.draft.enabled` for ALL root/header entities (NOT child/composition entities) to support Fiori Elements edit flows.
   - Define custom actions for every business rule:
     - `action approve() returns Boolean;` (bound to entity)
     - `function getDashboard() returns array of DashboardItem;` (unbound)
   - Add `@requires: 'authenticated-user'` at service level

2. ANNOTATIONS (srv/annotations.cds):
   Generate COMPLETE, robust annotations for EVERY entity. This makes the app "Enterprise Ready":

   a) @Capabilities — Secure APIs:
      - Add `@Capabilities.Insertable: false` and `Updatable: false` for read-only tracking log entities.
      - Add `@Capabilities.Deletable: false` for critical core entities.

   b) UI.HeaderInfo — entity title/description for Object Page header:
      ```cds
      UI.HeaderInfo: {
          TypeName: 'Order',
          TypeNamePlural: 'Orders',
          Title: { Value: orderNumber },
          Description: { Value: status }
      }
      ```

   c) UI.LineItem — columns for List Report table:
      - Include 6-10 most important fields
      - Add `![@UI.Importance]: #High` for key fields
      - MUST include status and amount/date fields if they exist.

   d) UI.SelectionFields — filter bar fields (3-5 searchable fields)

   e) UI.FieldGroup — grouped fields for Object Page sections

   f) UI.Facets — Object Page tabs/sections:
      - #GeneralInfo: key business fields
      - #Details: secondary fields
      - #Admin: created/modified fields with @readonly

   g) UI.DataPoint — KPI values in header (status, totals, ratings)

   h) @Common.ValueList — Value help for association/enum fields

   i) @Common.SideEffects — reactive form updates

OUTPUT FORMAT:
Return a JSON object:
{
    "service_cds": "... srv/service.cds content ...",
    "annotations_cds": "... srv/annotations.cds content ..."
}
Return ONLY the JSON."""


SERVICE_GENERATION_PROMPT = """Generate a complete SAP CAP service definition and Fiori annotations.

Project Name: {project_name}
Namespace: {namespace}
OData Version: {odata_version}
Draft Enabled: {draft_enabled}
Service Name: {service_name}
Service Path: /{service_path}

{schema_context}

ENTITIES:
{entities_json}

RELATIONSHIPS:
{relationships_json}

BUSINESS RULES:
{business_rules_json}

REQUIREMENTS:
1. srv/service.cds:
   - Import from '../db/schema'
   - Create projections for ALL entities
   - Enable @odata.draft.enabled on root entities only
   - Define custom actions/functions for business rules
   - Add service-level auth annotation

2. srv/annotations.cds:
   - COMPLETE UI annotations for EVERY entity
   - UI.HeaderInfo, UI.LineItem, UI.SelectionFields, UI.FieldGroup, UI.Facets, UI.DataPoint
   - @Common.ValueList for associations and enum fields
   - @Common.SideEffects where applicable
   - @Capabilities restrictions for child/read-only entities

Respond with ONLY valid JSON."""


# =============================================================================
# Main Agent Function
# =============================================================================

async def service_exposure_agent(state: BuilderState) -> BuilderState:
    """
    CAP Service Exposure Agent (LLM-Driven)

    Uses LLM to generate production-quality service definitions and annotations.
    Reads actual schema.cds from data modeling agent for consistency.

    Generates:
    1. srv/service.cds - Service definition with projections, draft, and actions
    2. srv/annotations.cds - Deep Fiori annotations
    3. srv/index.cds - Service index
    """
    logger.info("Starting Service Exposure Agent (LLM-Driven)")

    now = datetime.utcnow().isoformat()
    errors: list[ValidationError] = []
    generated_files: list[GeneratedFile] = []

    state["current_agent"] = "service_exposure"
    state["updated_at"] = now
    state["current_logs"] = []

    log_progress(state, "Starting service exposure phase...")

    entities = state.get("entities", [])
    if not entities:
        log_progress(state, "Error: No entities found for service exposure.")
        state["validation_errors"] = state.get("validation_errors", []) + errors
        return state

    namespace = state.get("project_namespace", "com.company.app")
    project_name = state.get("project_name", "App")
    odata_version = state.get("odata_version", ODataVersion.V4.value)
    draft_enabled = state.get("draft_enabled", True)
    relationships = state.get("relationships", [])
    business_rules = state.get("business_rules", [])

    # Build service name
    service_name = "".join(
        word.capitalize()
        for word in project_name.replace("-", " ").replace("_", " ").split()
    )
    service_name = f"{service_name}Service"
    service_path = project_name.lower().replace(" ", "-")

    # Get inter-agent context
    schema_context = get_schema_context(state)
    knowledge = get_service_knowledge()

    prompt = SERVICE_GENERATION_PROMPT.format(
        project_name=project_name,
        namespace=namespace,
        odata_version=odata_version,
        draft_enabled=draft_enabled,
        service_name=service_name,
        service_path=service_path,
        schema_context=schema_context or "(schema not yet available)",
        entities_json=json.dumps(entities, indent=2),
        relationships_json=json.dumps(relationships, indent=2),
        business_rules_json=json.dumps(business_rules, indent=2),
    )

    # Inject knowledge into prompt
    prompt = f"{knowledge}\n\n{prompt}"

    # Self-Healing: Inject correction context if present
    correction_context = state.get("correction_context")
    if state.get("needs_correction") and state.get("correction_agent") == "service_exposure" and correction_context:
        log_progress(state, "Applying self-healing correction context from validation agent...")
        correction_prompt = correction_context.get("correction_prompt", "")
        if correction_prompt:
            prompt = f"CRITICAL CORRECTION REQUIRED:\n{correction_prompt}\n\nORIGINAL INSTRUCTIONS:\n{prompt}"

    log_progress(state, "Calling LLM for service definition generation...")

    result = await generate_with_retry(
        prompt=prompt,
        system_prompt=SERVICE_SYSTEM_PROMPT,
        state=state,
        required_keys=["service_cds"],
        max_retries=3,
        agent_name="service_exposure",
    )

    if result and result.get("service_cds"):
        service_content = result["service_cds"]

        if "service" in service_content.lower():
            generated_files.append({
                "path": "srv/service.cds",
                "content": service_content,
                "file_type": "cds",
            })
            log_progress(state, "✅ Generated service definition.")

            if result.get("annotations_cds"):
                generated_files.append({
                    "path": "srv/annotations.cds",
                    "content": result["annotations_cds"],
                    "file_type": "cds",
                })
                log_progress(state, "✅ Generated Fiori annotations.")
        else:
            log_progress(state, "⚠️ LLM service missing required elements. Generating minimal service.")
            generated_files.extend(_minimal_service_files(entities, namespace, service_name, service_path, relationships, draft_enabled))
    else:
        log_progress(state, "⚠️ LLM generation failed. Generating minimal service.")
        generated_files.extend(_minimal_service_files(entities, namespace, service_name, service_path, relationships, draft_enabled))
        errors.append({
            "agent": "service_exposure",
            "code": "LLM_FAILED",
            "message": "LLM service generation failed. Minimal service generated.",
            "field": None,
            "severity": "warning",
        })

    # Add index.cds
    generated_files.append({
        "path": "srv/index.cds",
        "content": "using from './service';\nusing from './annotations';\n",
        "file_type": "cds",
    })

    # Store inter-agent context
    store_generated_content(state, generated_files, {
        "service.cds": "generated_service_cds",
        "annotations.cds": "generated_annotations_cds",
    })

    # Update state
    state["artifacts_srv"] = generated_files
    state["validation_errors"] = state.get("validation_errors", []) + errors
    state["needs_correction"] = False

    state["agent_history"] = state.get("agent_history", []) + [{
        "agent_name": "service_exposure",
        "status": "completed",
        "started_at": now,
        "completed_at": datetime.utcnow().isoformat(),
        "duration_ms": None,
        "error": None,
        "logs": state.get("current_logs", []),
    }]

    log_progress(state, f"Service exposure complete. Generated {len(generated_files)} files.")
    return state


# =============================================================================
# Minimal Fallback
# =============================================================================

def _is_child_entity(entity_name: str, relationships: list) -> bool:
    """Check if entity is a composition child."""
    for rel in relationships:
        if rel.get("type") == "composition" and rel.get("target_entity") == entity_name:
            return True
    return False


def _minimal_service_files(
    entities: list,
    namespace: str,
    service_name: str,
    service_path: str,
    relationships: list,
    draft_enabled: bool,
) -> list[GeneratedFile]:
    """Generate minimal valid service files."""
    # Service CDS
    lines = [
        f"using {{ {namespace} as db }} from '../db/schema';",
        "",
        f"service {service_name} @(path: '/{service_path}') {{",
    ]
    for entity in entities:
        name = entity.get("name", "")
        is_child = _is_child_entity(name, relationships)
        draft_ann = " @odata.draft.enabled" if draft_enabled and not is_child else ""
        lines.append(f"  entity {name} as projection on db.{name}{draft_ann};")
    lines.append("}")

    service_content = "\n".join(lines)

    # Minimal annotations
    ann_lines = [f"using {service_name} from './service';", ""]
    for entity in entities:
        name = entity.get("name", "")
        fields = entity.get("fields", [])
        field_names = [f.get("name", "") for f in fields if f.get("name") != "ID"][:6]

        ann_lines.append(f"annotate {service_name}.{name} with @(")
        ann_lines.append(f"  UI.HeaderInfo: {{")
        ann_lines.append(f"    TypeName: '{name}',")
        ann_lines.append(f"    TypeNamePlural: '{name}s',")
        if field_names:
            ann_lines.append(f"    Title: {{ Value: {field_names[0]} }}")
        ann_lines.append(f"  }},")
        ann_lines.append(f"  UI.LineItem: [")
        for fn in field_names[:5]:
            ann_lines.append(f"    {{ Value: {fn} }},")
        ann_lines.append(f"  ]")
        ann_lines.append(f");")
        ann_lines.append("")

    annotations_content = "\n".join(ann_lines)

    return [
        {"path": "srv/service.cds", "content": service_content, "file_type": "cds"},
        {"path": "srv/annotations.cds", "content": annotations_content, "file_type": "cds"},
    ]
